### ISSUE TITLE
ステータス＆測定データAPIの送信データ形式決め

### ISSUE THREAD

**Issue by saitoiotken** [IoT-Study/acacia-server-documents#2]
## 概要
中継器からの送信データ形式を決定したいです。

## 詳細

1. ステータスAPIと測定データAPIの送信データ形式をapi_relay.mdに記載してください。
作業ブランチ ``` feature/gh-2```
https://github.com/IoT-Study/acacia-server-documents/blob/feature/gh-2/Specifications/api_relay.md

2. ステータスAPIと測定データAPIの送信頻度をこのIsuuesに記載してください。
> e.x.
> - ステータスAPI: 1秒ごと 
> - 測定データAPI: 30秒ごと （Waypointごと）

ステータス送信APIと測定データ送信APIは、送信頻度が違うと思われるので別にしてありますが、送信頻度が同じならまとめて１本にしてしまって問題ないです。

### 期限
 - 2018年5月会
   - サーバ構成とDBの見積もりに必要なため、早めに記載よろしくお願いいたいます。

## 参考資料
なし

**Comment by koutarou-akiyoshi** [comment]
`2. ステータスAPIと測定データAPIの送信頻度`

サーバーの課金を考えると、1測定につき1回のAPIコールにできればと思う。
中継機で測定中にデータを溜め込んで、測定完了した時にサーバーへ送信するといった具合に。

**Comment by saitoiotken** [comment]
@okunagak 
APIの設計ですが、従来はGCE（サーバ側の中継）に対して、JSON-RPCで送信してもらう予定でしたが、この方法だとサーバ班の工数が大きくなりそうです。
そこで、
 - 中継器から直接REST APIでRealtime Databaseへ送信してもらうことを検討したいです。

https://firebase.google.com/docs/database/rest/start?hl=ja

同じ理由で、 
- ステータス送信APIと測定データ送信APIの２つもまとめる方向で検討したいです。

最低限、Waypointの測定データが取れれば良いかと思うので、測定データ送信APIのみで、
測定完了後に測定したWaypointの温度・湿度・不快指数をまとめて送ってもらうと助かります。

上記２点、ご検討よろしくお願いします。

**Comment by saitoiotken** [comment]
(2017/5 iot会)
ステータスAPIはいらない。

## 測定データ送信API
 - いくつか、まとめて送ります。
 - 詳細は中継班で決定！
## 頻度
 - 1秒以上

**Comment by saitoiotken** [comment]
マージ済みのためcloseします。
