### ISSUE TITLE
アプリのRemote Config初期値

### ISSUE THREAD

**Issue by saitoiotken** [IoT-Study/acacia-server-documents#4]
## 概要
アプリのRemote Configの初期値を指定してください。
※Remote Configを使用しない、または、初期値が不要の場合は、不使用の旨記載してください。

## 詳細
アプリではfirebaseを利用するためAPIは不要ですが、サーバ側で初期値を設定できます。
設定できる値はJSON(key-value)形式です。初期値をこのIssueに記載してください。
> e.x.
```
{
    "device_id": "abc",
    "count": 123,
    "enable": true
}
```
## 参考資料
https://firebase.google.com/docs/remote-config/?hl=ja

**Comment by koutarou-akiyoshi** [comment]
**Remote Config**は使うケースが無いように思います。
参考資料の**主な機能**の箇所にあるような使い方が、このプロジェクトのシステムでは無いように思えるので。

**Comment by saitoiotken** [comment]
@koutarou-akiyoshi 
> 参考資料の主な機能の箇所にあるような使い方が、このプロジェクトのシステムでは無いように思えるので。

ご指摘の通り、必須の機能ではないので、工数が足りなければ削る予定です。

**Comment by saitoiotken** [comment]
利用しないため、closeします。
