### ISSUE TITLE
サーバ班の経費見積

### ISSUE THREAD

**Issue by saitoiotken** [IoT-Study/acacia-server-documents#6]
## 概要
サーバ班で必要な物品＆サービスの見積もりをします。

## 詳細
当面はFirebaseの無料版を利用する予定ですが、Bigqueryの連携を考慮して有料版の使用も検討しておきます。

- Firebase料金
  - GCPとの連携
- GCP料金
  - Bigquery
  - Cloud Storage
  - GCE
- その他
  - 他にも必要な物品があれば価格とともにこのIssueに追記してください 
> e.x
> 鉛筆 100円

## 参考資料
https://firebase.google.com/pricing/?hl=ja
https://cloud.google.com/pricing/?hl=ja

**Comment by saitoiotken** [comment]
## 料金
月額料金
### Realtime Database
  - 保存  $5/GB
（無料枠 1 GB）
  - ダウンロード済み  $1/GB
（無料枠 10 GB）

### BigQuery
 - ストレージ $0.02 / GB/月 
（無料枠毎月 10 GB）
 - クエリ $5 / TB　
（無料枠毎月 1 TB）

### GCE
 - 同一リージョン内のゾーン間の下り $0.01 / GB
 - US 内のリージョン間の下り $0.01 / GB
 - ネットワーク（下り） $0.12 / GB
   - 無料枠
     - f1-micro インスタンス（1 か月あたり、米国リージョンのみ）
     - 30 GB の HDD（期間合計）
     - 5 GB のスナップショット（期間合計）
     - 1 GB の北米から全リージョン宛て下りネットワーク（1 か月あたり、中国およびオーストラリアを除く）

## 見積もり
### Firebase
 - 無料枠に収まる？

### BigQuery
 - 1ヶ月でのデータ保管量
  - 250 Bを1秒間隔で8時間4日間保存と想定
250 B * 3600 s * 8 h * 4日 = 28.8 MB
 - 1ヶ月で利用可能なクエリ数
1 T/ 28.8 MB = 34722 回

### GCE
 - 無料枠に収まる？

**Comment by koutarou-akiyoshi** [comment]
↑ の見積もり内容でよさそう
BIgQueryは、データの出し入れ頻度をうまくやれば、もう少し抑えられるかも。

**Comment by saitoiotken** [comment]
## 見積もり
0円/月

## 懸念点
保存するデータ量、APIコール回数が不明のため、正確な見積もりができていない。

**Comment by saitoiotken** [comment]
2018/5月会で報告済みのため、closeします。
