### ISSUE TITLE
サーバーシステム構成

### ISSUE THREAD

**Issue by saitoiotken** [IoT-Study/acacia-server-documents#7]
## 概要
システム構成を検討します。

## 詳細
 - Firebase

## 参考資料
https://github.com/IoT-Study/acacia-server-documents/blob/master/Documents/overview.md

**Comment by saitoiotken** [comment]
工数削減のために、GCEいらないかも。
懸念点としては、SecretをH/W側が持つことになるので、セキュリティ的によろしくない。

**Comment by koutarou-akiyoshi** [comment]
GCEは使わずにやれそうですね。

アプリはFirebase SDKが認証と通信を処理するので問題なさそうですが、懸念があるのは中継機でのRESTによるAPIコールでしょうか。
中継機の測定データをアプリ経由にすると、この部分の懸念は解決できるかなとは思います。（また、システム構成の見直しになりますが）

**Comment by saitoiotken** [comment]
> アプリはFirebase SDKが認証と通信を処理するので問題なさそうですが、懸念があるのは中継機でのRESTによるAPIコールでしょうか。

そうですね、中継器→Firebaseが問題ですね。5月会でIoTセキュリティの検討するみたいなので、GCEをかまさず直接行けるか話してみます。

> 中継機の測定データをアプリ経由にすると、この部分の懸念は解決できるかなとは思います。（また、システム構成の見直しになりますが）

アプリ経由にするとすごい楽なんですが、測定中放置したいという要求があり、中継器→サーバを無くすのは難しいです。

**Comment by saitoiotken** [comment]
中継器側で測定ごとにデータをまとめてくれるなら、Realtime Databaseを使う必要はなくて、Cloud Storage使う方が安くて良いかもと思いました。
https://firebase.google.com/docs/storage/?hl=ja

**Comment by saitoiotken** [comment]
（2018/5 IoT会）
ステータスAPIはなしでOK

**Comment by saitoiotken** [comment]
（2018/5 IoT会）
中継器とサーバの接続は不要です。

**Comment by saitoiotken** [comment]
#17でサーバ構成決定済みのため、closeします。
